#!/bin/bash
CP=lib:lib/@@H1-JAR@@:@@CLASSPATH@@
LAUNCH_COMMAND="java -classpath $CP -Xms128m -Xmx512m -Dcom.talis.plaftform.sequencing.zookeeper.servers=/zkservers com.talis.platform.sequencing.http.SequenceServer"
