#!/bin/bash
CP=lib:lib/@@H1-JAR@@:@@CLASSPATH@@
LAUNCH_COMMAND="java -javaagent:./lib/jmxetric-patch-0.1-patch-4.jar=host=127.0.0.1,port=8649,config=jmxetric.xml,process=SequenceServer -classpath $CP -Xms128m -Xmx512m -Dfile-encoding=UTF-8 -Djavax.net.ssl.keyStore=./security/.h1-jmx-server-keystore -Djavax.net.ssl.keyStorePassword=bl1ng441S -Djavax.net.ssl.trustStore=./security/.hi-jmx-server-keystore -Djavax.net.ssl.trustStorePassword=bl1ng441S com.talis.platform.sequencing.http.SequenceServer'"

